### ISSUE TITLE
run not on win7

### ISSUE THREAD

**Issue by thoralf2002** [forrest79/gmusic79unofficalplayer#1]
Problemsignatur:
  Problemereignisname:	CLR20r3
  Problemsignatur 01:	gmusic79.exe
  Problemsignatur 02:	1.0.0.0
  Problemsignatur 03:	5436abde
  Problemsignatur 04:	GMusic79UnofficialPlayer
  Problemsignatur 05:	1.0.0.0
  Problemsignatur 06:	5436abde
  Problemsignatur 07:	7
  Problemsignatur 08:	34
  Problemsignatur 09:	System.NullReferenceException
  Betriebsystemversion:	6.1.7601.2.1.0.768.3
  Gebietsschema-ID:	1031

**Comment by forrest79** [comment]
I run it on Windows 7

**Comment by thoralf2002** [comment]
Betriebsystemversion: 6.1.7601.2.1.0.768.3 = win7 - i have 64bit Home Version - with newest Updates
